MERGE: -c 34172 /branches/lwidentity-5.1rc -> /branches/lwidentity-5.1
Check in experiemental patch to fix SLED 11 domainjoin

(domainjoin: r34440)

diff --git a/domainjoin/scripts/ConfigureLogin.in b/domainjoin/scripts/ConfigureLogin.in
--- a/domainjoin/scripts/ConfigureLogin.in
+++ b/domainjoin/scripts/ConfigureLogin.in
@@ -142,6 +142,19 @@ if [ $? -ne 0 ]; then
     alias seq=seq_replacement
 fi
 
+ShowError()
+{
+    __output="`"$@" 2>&1`"
+    __rc="$?"
+
+    if [ "$__rc" -ne 0 ]
+    then
+	echo "$__output" >&2
+    fi
+
+    return "$__rc"
+}
+
 Help()
 {
     echo "usage: $0 nsswitch_restart"
@@ -164,71 +177,74 @@ GetDistroVersion()
 
 GracefulSSHDRestart()
 {
-# can't just restart sshd, 'cause that would tear down
-# the remote installer session, so we need to SIGHUP just
-# the parent sshd process. However, on SuSE that file
-# is called /var/run/sshd.init.pid, and on RedHat it is
-# /var/run/sshd.pid...|
-    result=0
-    files=`ls /var/run/sshd*.pid 2> /dev/null`
-    shouldBeRunning=0
-    stillRunning=0
-    if [ -n "$files" ]; then
-        for pidfile in "$files"; do
-            if [ -f "$pidfile" ]; then
-                shouldBeRunning=1
-                sshdpid=`cat $pidfile`
-                kill -HUP $sshdpid || result=$?
+    if [ -x /etc/init.d/sshd ]; then
+	ShowError /etc/init.d/sshd restart
+    elif [ -x /etc/init.d/ssh ]; then
+	ShowError /etc/init.d/ssh restart
+    else
+	# Can't find an appropriate init script, try
+	# finding the pid and sending SIGHUP instead
+	result=0
+	files=`ls /var/run/sshd*.pid 2> /dev/null`
+	shouldBeRunning=0
+	stillRunning=0
+	if [ -n "$files" ]; then
+            for pidfile in "$files"; do
+		if [ -f "$pidfile" ]; then
+                    shouldBeRunning=1
+                    sshdpid=`cat $pidfile`
+                    kill -HUP $sshdpid || result=$?
                 # We want this daemon to restart and change pids, so we'll
                 # wait up to 15 seconds for that to happen
-                for count in `seq 15`; do
-                    ps -p $sshdpid >/dev/null 2>&1 || break
-                done
-            fi
-        done
-        if [ $shouldBeRunning -ne 0 ]; then
+                    for count in `seq 15`; do
+			ps -p $sshdpid >/dev/null 2>&1 || break
+                    done
+		fi
+            done
+            if [ $shouldBeRunning -ne 0 ]; then
             # sshd on SuSE 9.0 and 8.2 have a bug that causes it to die on a
 	    # SIGHUP. So try starting sshd in that case.
-            for pidfile in "$files"; do
-                if [ -f "$pidfile" ] && ps -p `cat $pidfile` >/dev/null 2>&1
-                then
-                    stillRunning=1
-                fi
-            done
-            if [ $stillRunning -eq 0 ]; then
+		for pidfile in "$files"; do
+                    if [ -f "$pidfile" ] && ps -p `cat $pidfile` >/dev/null 2>&1
+                    then
+			stillRunning=1
+                    fi
+		done
+		if [ $stillRunning -eq 0 ]; then
                 # It died
-                /etc/init.d/sshd start > /dev/null 2>&1
+                    /etc/init.d/sshd start > /dev/null 2>&1
+		fi
             fi
-        fi
-    elif [ -x /usr/bin/lssrc ]; then
+	elif [ -x /usr/bin/lssrc ]; then
         # This is an AIX system. We have to use lssrc to get SSHD's pid.
         # lssrc returns the output in this form:
         # Subsystem   Group   PID  Status
         #  sshd       ssh     123  active
-        sshdpid=""
-        sshdstatus="`/usr/bin/lssrc -s sshd`"
-        if [ $? -eq 0 ]; then
-            sshdpid=`echo "$sshdstatus" | tail -1 | awk '{ print $3 }'`
-        fi
-        if [ -n "$sshdpid" ]; then
+            sshdpid=""
+            sshdstatus="`/usr/bin/lssrc -s sshd`"
+            if [ $? -eq 0 ]; then
+		sshdpid=`echo "$sshdstatus" | tail -1 | awk '{ print $3 }'`
+            fi
+            if [ -n "$sshdpid" ]; then
             # Let's double check that the pid is valid. It could say
             # "inoperative".
-            ps -p "$sshdpid" >/dev/null 2>&1
-            if [ $? -ne 0 ]; then
+		ps -p "$sshdpid" >/dev/null 2>&1
+		if [ $? -ne 0 ]; then
                 # The pid isn't valid
-                sshdpid=""
+                    sshdpid=""
+		fi
             fi
-        fi
-        if [ -n "$sshdpid" ]; then
-            kill -HUP "$sshdpid" || result=$?
+            if [ -n "$sshdpid" ]; then
+		kill -HUP "$sshdpid" || result=$?
         else
+		echo "sshd does not appear to be running"
+            fi
+	else
             echo "sshd does not appear to be running"
-        fi
-    else
-        echo "sshd does not appear to be running"
-    fi
+	fi
     # Ignore kill errors because .pid files may have been orphaned.
-    return 0
+	return 0
+    fi
 }
 
 ForceNetworkManagerRunning()
@@ -340,10 +356,6 @@ GracefulDbusRestart()
 	uidlist=`GetCkUidSessionList`
         if [ "$distroType" = "SuSE" -o "$distroType" = "OpenSuSE" -o "$distroType" = "SLES" -o "$distroType" = "SLED" ]; then
             if IsUserLoggedInX; then
-                if [ "$1" = "1" ]; then
-                    echo "Warning: unable to restart dbus on this system while a user is logged in graphically via gdm. Until dbus is restarted, graphical logins as domain users will be unpredicatable. Please reboot your computer or log out of X windows, then run these commands to restart dbus:" >&2
-                    echo "/etc/init.d/dbus restart; killall gdm; /etc/init.d/xdm restart" >&2
-                fi
                 return 1
             else
                 # Restarting dbus kills gdm
@@ -380,10 +392,6 @@ GracefulDbusRestart()
         # Fedora is the only known system that has /etc/init.d/messagebus
         if [ "$distroType" = "Fedora" -a `GetDistroVersion` -ge 9 ]; then
             if IsUserLoggedInX; then
-                if [ "$1" = "1" ]; then
-                    echo "Warning: unable to restart dbus on this system while a user is logged in graphically via gdm. Until dbus is restarted, graphical logins as domain users will be unpredicatable. Please reboot your computer or log out of X windows, then run these commands to restart dbus:" >&2
-                    echo "/etc/init.d/messagebus restart; gdm-restart" >&2
-                fi
                 return 1
             fi
         fi
@@ -397,8 +405,7 @@ GracefulDbusRestart()
 
 GracefulCronRestart()
 {
-   sh ${LIBEXECDIR}/gpcron restart 
-   return $?
+    ShowError sh ${LIBEXECDIR}/gpcron restart
 }
 
 IsProcessRunning()
@@ -418,16 +425,15 @@ GracefulNscdRestart()
 {
     _is_nscd_running=0
     if [ -x /etc/init.d/nscd ]; then
-        /etc/init.d/nscd status 2>&1 >/dev/null
+        /etc/init.d/nscd status >/dev/null 2>&1
         if [ $? -eq 0 ]; then
             _is_nscd_running=1
         elif IsProcessRunning nscd ; then
             _is_nscd_running=1
         fi
         if [ $_is_nscd_running -ne 0 ]; then
-            echo "Restarting nscd"
-            /etc/init.d/nscd stop
-            /etc/init.d/nscd start
+            ShowError /etc/init.d/nscd stop
+            ShowError /etc/init.d/nscd start
         fi
     fi
     return 0
@@ -486,21 +492,21 @@ GracefulXDMRestart()
 	# try to hack around RedHat systems
 	# Try to schedule a safe restart first
 	if [ -x "/opt/gnome/sbin/gdm-safe-restart" ]; then
-	    /opt/gnome/sbin/gdm-safe-restart
+	    ShowError /opt/gnome/sbin/gdm-safe-restart
 	elif [ -x "/usr/sbin/gdm-safe-restart" ]; then
-	    /usr/sbin/gdm-safe-restart
+	    ShowError /usr/sbin/gdm-safe-restart
 	elif [ -x "/usr/X11R6/sbin/gdm-safe-restart" ]; then
-	    /usr/X11R6/sbin/gdm-safe-restart
+	    ShowError /usr/X11R6/sbin/gdm-safe-restart
         elif [ -x "/etc/init.d/gdm" ]; then
-            /etc/init.d/gdm reload 2>&1
+            ShowError /etc/init.d/gdm reload
 	elif [ $userViaX -eq 1 ]; then
 	    # no user logged in via X -- bounce the puppy
 	    if [ -x "/opt/gnome/sbin/gdm-restart" ]; then
-		/opt/gnome/sbin/gdm-restart
+		ShowError /opt/gnome/sbin/gdm-restart
 	    elif [ -x "/usr/sbin/gdm-restart" ]; then
-		/usr/sbin/gdm-restart
+		ShowError /usr/sbin/gdm-restart
             elif [ -x "/etc/init.d/gdm" ]; then
-                /etc/init.d/gdm restart
+                ShowError /etc/init.d/gdm restart
 	    else
 		echo "Could not find gdm-restart. Please restart your X server manually"
 		echo "Continuing with domain join."
@@ -576,7 +582,7 @@ NsswitchRestart()
     fi
     
     if not GracefulDbusRestart 1; then
-        echo "Error occurred while restarting system message bus (dbus)" >&2
+        echo "Could not restart dbus automatically.  You must restart your system before Active Directory users may log in graphically." >&2
         nsswitch_rc=1
     fi
 
