openldap: Renaming openldap-2.4.16 to openldap
(openldap: r35641)

diff --git a/openldap/tests/scripts/test026-dn b/openldap/tests/scripts/test026-dn
--- a/openldap/tests/scripts/test026-dn
+++ b/openldap/tests/scripts/test026-dn
@@ -1,7 +1,8 @@
 #! /bin/sh
+# $OpenLDAP: pkg/ldap/tests/scripts/test026-dn,v 1.13.2.6 2009/01/22 00:01:19 kurt Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 2004-2006 The OpenLDAP Foundation.
+## Copyright 2004-2009 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -55,7 +56,7 @@ cat /dev/null > $SEARCHOUT
 
 echo "Searching database..."
 echo "# Searching database..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 >> $SEARCHOUT 2>&1
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 >> $SEARCHOUT 2>&1
 
 RC=$?
 if test $RC != 0 ; then
@@ -67,7 +68,7 @@ fi
 DN="OU=Sales+CN=J. Smith,DC=example,DC=net"
 echo "Searching database for DN=\"$DN\"..."
 echo "# Searching database for DN=\"$DN\"..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	"(member=$DN)" >> $SEARCHOUT 2>&1
 
 RC=$?
@@ -80,7 +81,7 @@ fi
 DN="testUUID=597ae2f6-16a6-1027-98f4-ABCDEFabcdef,DC=Example"
 echo "Searching database for entryUUID-named DN=\"$DN\"..."
 echo "# Searching database for entryUUID-named DN=\"$DN\"..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	"(member=$DN)" \
 	>> $SEARCHOUT 2>&1
 
@@ -94,7 +95,7 @@ fi
 DN="dc=example,dc=com"
 echo "Searching database for nameAndOptionalUID=\"$DN\"..."
 echo "# Searching database for nameAndOptionalUID=\"$DN\"..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	"(uniqueMember=$DN)" >> $SEARCHOUT 2>&1
 
 RC=$?
@@ -107,7 +108,20 @@ fi
 DN="dc=example,dc=com#'001000'B"
 echo "Searching database for nameAndOptionalUID=\"$DN\"..."
 echo "# Searching database for nameAndOptionalUID=\"$DN\"..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+	"(uniqueMember=$DN)" >> $SEARCHOUT 2>&1
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+DN="dc=example,dc=com#'1000'B"
+echo "Searching database for nameAndOptionalUID=\"$DN\"..."
+echo "# Searching database for nameAndOptionalUID=\"$DN\"..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	"(uniqueMember=$DN)" >> $SEARCHOUT 2>&1
 
 RC=$?
@@ -118,9 +132,9 @@ if test $RC != 0 ; then
 fi
 
 DN="dc=example,dc=com"
-echo "Searching database for uniqueMember~=\"$DN\" (approx) ..."
-echo "# Searching database for uniqueMember~=\"$DN\" (approx) ..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+echo "Searching database for uniqueMember~=\"$DN\" (approx)..."
+echo "# Searching database for uniqueMember~=\"$DN\" (approx)..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	"(uniqueMember~=)" >> $SEARCHOUT 2>&1
 
 RC=$?
@@ -130,10 +144,10 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-DN="dc=example,dc=com#'001000'B"
-echo "Searching database for uniqueMember~=\"$DN\" (approx) ..."
-echo "# Searching database for uniqueMember~=\"$DN\" (approx) ..." >> $SEARCHOUT
-$LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
+DN="dc=example,dc=com#'1000'B"
+echo "Searching database for uniqueMember~=\"$DN\" (approx)..."
+echo "# Searching database for uniqueMember~=\"$DN\" (approx)..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	"(uniqueMember~=$DN)" >> $SEARCHOUT 2>&1
 
 RC=$?
@@ -145,12 +159,12 @@ fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
-LDIFOUT=$DNOUT
-
 echo "Filtering ldapsearch results..."
 . $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+echo "Filtering original data..."
+. $LDIFFILTER < $DNOUT > $LDIFFLT
 echo "Comparing ldapsearch results against original..."
-$CMP $SEARCHFLT $LDIFOUT > $CMPOUT
+$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
 if test $? != 0 ; then
 	echo "comparison failed - DN write operations did not complete correctly"
@@ -160,4 +174,7 @@ fi
 #####
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/openldap/tests/scripts/test033-glue-syncrepl b/openldap/tests/scripts/test033-glue-syncrepl
--- a/openldap/tests/scripts/test033-glue-syncrepl
+++ b/openldap/tests/scripts/test033-glue-syncrepl
@@ -1,7 +1,8 @@
 #! /bin/sh
+# $OpenLDAP: pkg/ldap/tests/scripts/test033-glue-syncrepl,v 1.17.2.6 2009/03/05 22:19:39 quanah Exp $ */
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2009 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -12,10 +13,10 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-if test "$BACKEND" != "bdb" && test "$BACKEND" != "hdb" ; then
-	echo "Test does not support $BACKEND"
+case $BACKEND in bdb | hdb | ldif) : ;; *)
+	echo "Test does not support $BACKEND backend, test skipped"
 	exit 0
-fi
+esac
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
@@ -36,7 +37,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-rm -f $DBDIR1A/* $DBDIR1B/*
+rm -rf $DBDIR1A/* $DBDIR1B/*
 cp -pr $DBDIR1C $DBDIR2C
 
 echo "Starting slapd 1 on TCP/IP port $PORT1..."
@@ -132,9 +133,8 @@ case $RC in
 	;;
 esac
 
-SLEEP=15
-echo "Waiting $SLEEP seconds for shadow subtrees to sync..."
-sleep $SLEEP
+echo "Waiting $SLEEP1 seconds for shadow subtrees to sync..."
+sleep $SLEEP1
 
 echo "Filtering original ldif used to create database..."
 . $LDIFFILTER < $GLUESYNCOUT > $LDIFFLT
@@ -163,7 +163,31 @@ for P in $PORT1 $PORT2 ; do
 	fi
 done
 
+echo "Testing ldapdelete propagation..."
+$LDAPDELETE -D "cn=Manager 1,$BASEDN" -w $PASSWD -H $URI1 "$BABSDN" \
+	> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapdelete failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+# This usually propagates immediately
+sleep 1
+
+$LDAPSEARCH -H $URI2 -b "$BABSDN" > $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+fi
+
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
diff --git a/openldap/tests/scripts/test037-manage b/openldap/tests/scripts/test037-manage
--- a/openldap/tests/scripts/test037-manage
+++ b/openldap/tests/scripts/test037-manage
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test037-manage,v 1.8.2.4 2006/01/03 22:16:29 kurt Exp $
+# $OpenLDAP: pkg/ldap/tests/scripts/test037-manage,v 1.12.2.8 2009/02/22 05:50:54 quanah Exp $
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2006 The OpenLDAP Foundation.
+## Copyright 1998-2009 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -15,6 +15,11 @@
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
+
+if test $BACKEND = "ldif" ; then
+	echo "LDIF backend does not support relax control, test skipped"
+	exit 0
+fi
 
 mkdir -p $TESTDIR $DBDIR1
 
@@ -56,23 +61,9 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-# ITS#3898: #ifndef LDAP_DEVEL, the control is not available
-MANAGEDITOID="1.3.6.1.4.1.4203.666.5.12"
-case `$LDAPSEARCH -s base -b "" -h $LOCALHOST -p $PORT1 \
-	'(supportedControl:objectIdentifierMatch:='${MANAGEDITOID}')' \
-	supportedControl | grep "supportedControl: ${MANAGEDITOID}"` in
-"supportedControl: ${MANAGEDITOID}")
-	;;
-*)
-	echo "The \"manageDIT\" control appears to be unsupported; test disabled"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit 0
-	;;
-esac
-
 echo "Testing modify, add, and delete..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
-	-e \!manageDIT > \
+	-e \!relax > \
 	$TESTOUT 2>&1 << EOMODS
 version: 1
 #
@@ -139,22 +130,9 @@ createTimestamp: 19700101000000Z
 modifiersName: cn=Someone Else
 modifyTimestamp: 19700101000000Z
 entryUUID: badbadef-dbad-1029-92f7-badbadbadbad
-EOMODS
 
-RC=$?
-if test $RC != 0 ; then
-	echo "ldapmodify failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-echo "Testing modify, add, and delete..."
-$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
-	-e \!manageDIT > \
-	$TESTOUT 2>&1 << EOMODS
-version: 1
 #
-# Non-working tests
+# Tests that did not work until ITS#5792
 #
 
 dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
@@ -163,9 +141,8 @@ dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
 changetype: modify
 replace: objectClass
 objectClass: obsoletePerson
+objectClass: testPerson
 -
-replace: structuralObjectClass
-structuralObjectClass: testPerson
 
 dn: cn=James A Jones 1,ou=Alumni Association,ou=People,dc=example,dc=com
 # update structural object class of entry via objectClass add
@@ -173,8 +150,6 @@ changetype: modify
 add: objectClass
 objectClass: testPerson
 -
-replace: structuralObjectClass
-structuralObjectClass: testPerson
 
 dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 # update structural object class of entry via objectClass delete/add
@@ -185,17 +160,13 @@ objectClass: OpenLDAPperson
 add: objectClass
 objectClass: testPerson
 -
-delete: structuralObjectClass
--
-add: structuralObjectClass
-structuralObjectClass: testPerson
 EOMODS
 
 RC=$?
 if test $RC != 0 ; then
-	echo "ldapmodify failed ($RC)!  IGNORED"
-#	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-#	exit $RC
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
 fi
 
 echo "Using ldapsearch to retrieve all the entries..."
@@ -242,4 +213,7 @@ if test $? != 0 ; then
 fi
 
 echo ">>>>> Test succeeded"
+
+test $KILLSERVERS != no && wait
+
 exit 0
