For embedded build start lsass as part of lwsmd startup
Automatic Merge of CS: 49691 from likewise-stable to main

Automation: automerge=likewise-stable:main:49691
Testing Done: [Refer to original change.]
Bug Number: 1137785, 1173070
Reviewed by: ssalley
Approved by: mlo

Original Submittor:   erik
Original Description:
| For embedded build start lsass as part of lwsmd startup
|
| Automatic Merge of CS: 49690 from likewise-2015 to likewise-stable
|
| Automation: automerge=likewise-2015:likewise-stable:49690
| Testing Done: [Refer to original change.]
| Bug Number: 1137785, 1173070
| Reviewed by: ssalley
| Approved by: mlo
| Merge to: main: YES #
|
| Original Submittor:   erik
| Original Description:
| | For embedded build start lsass as part of lwsmd startup
| | Bonus: fix a seg-fault in cong2reg (doesn't imply conf2reg is working)
| |
| | Reviewer: ssalley, snambakam
| |
| | QA Notes:
| | Testing Done: lwsmd automatically launches lsass and rejoins domain
| | also verified that conf2reg no long seg-faults on ESX
| | [root@sea2-office-dhcp-97-240:~] /usr/lib/vmware/likewise/bin/lw-lsa get-status
| | Failed to query status from LSA service.  Error code 2 (ERROR_FILE_NOT_FOUND).
| | [root@sea2-office-dhcp-97-240:~] echo $?
| | 2
| | [root@sea2-office-dhcp-97-240:~] /etc/init.d/lwsmd start
| | Starting Likewise Service Manager [memory reservation set]  [starting lsass service] Starting service dependency: netlogon
| | Starting service dependency: lwio
| | Starting service dependency: rdr
| | Starting service: lsass
| | ...ok
| | [root@sea2-office-dhcp-97-240:~] esxcli network firewall ruleset list | grep  ac
| | tive
| | activeDirectoryAll     true
| | [root@sea2-office-dhcp-97-240:~] /usr/lib/vmware/likewise/bin/lw-lsa get-status
| | LSA Server Status:
| |
| | Compiled daemon version: 5.0.0.0
| | Packaged product version: 0.0.0.0
| | Uptime:        0 days 0 hours 0 minutes 29 seconds
| |
| | [Authentication provider: lsa-activedirectory-provider]
| |
| | 	Status:        Online
| | 	Mode:          Un-provisioned
| | 	Domain:        ERIKLAB.COM
| | 	Domain SID:    S-1-5-21-1637546655-2945625034-1138749992
| | 	Forest:        eriklab.com
| | 	Site:          Default-First-Site-Name
| | 	Online check interval:  300 seconds
| | 	[Trusted Domains: 1]
| |
| |
| | 	[Domain: ERIKLAB]
| |
| | 		DNS Domain:       eriklab.com
| | 		Netbios name:     ERIKLAB
| | 		Forest name:      eriklab.com
| | 		Trustee DNS name:
| | 		Client site name: Default-First-Site-Name
| | 		Domain SID:       S-1-5-21-1637546655-2945625034-1138749992
| | 		Domain GUID:      3371c506-ebd9-054a-aedc-55cbc603078f
| | 		Trust Flags:      [0x001d]
| | 		                  [0x0001 - In forest]
| | 		                  [0x0004 - Tree root]
| | 		                  [0x0008 - Primary]
| | 		                  [0x0010 - Native]
| | 		Trust type:       Up Level
| | 		Trust Attributes: [0x0000]
| | 		Trust Direction:  Primary Domain
| | 		Trust Mode:       In my forest Trust (MFT)
| | 		Domain flags:     [0x0001]
| | 		                  [0x0001 - Primary]
| |
| | 		[Domain Controller (DC) Information]
| |
| | 			DC Name:              WIN-DLUFU7RM0NP.eriklab.com
| | 			DC Address:           10.118.96.118
| | 			DC Site:              Default-First-Site-Name
| | 			DC Flags:             [0x0000f3fd]
| | 			DC Is PDC:            yes
| | 			DC is time server:    yes
| | 			DC has writeable DS:  yes
| | 			DC is Global Catalog: yes
| | 			DC is running KDC:    yes
| | [root@sea2-office-dhcp-97-240:~] echo $?
| | 0
| | [root@sea2-office-dhcp-97-240:~]
| | Documentation Notes:
| | Bug Number: 1137785, 1173070
| | Reviewed by: ssalley
| | Approved by: mlo
| | Mailto:
| | # Set "Merge to" values below to YES, SVS, NO, or MANUAL.
| | # If you're unsure, ask your manager or your peers, DO NOT guess.
| | Merge to: likewise-stable: YES #
| | Merge to: main: YES #

[git-p4: depot-paths = "//public/vmware-likewise-open-6-1/main/": change = 49692]

diff --git a/git-build/config/lwsmd b/git-build/config/lwsmd
--- a/git-build/config/lwsmd
+++ b/git-build/config/lwsmd
@@ -39,12 +39,40 @@ if [ "$PLATFORM" = "ESXI" ]; then
    PROG_ARGS="--syslog"
    PROG_ERR=/var/lib/likewise/lwsmd/lwsmd.err
    STARTHOOK="fix_locale"
+   POSTSTARTHOOK="start_lsass"
 fi
 
 fix_locale()
 {
     export LC_ALL="en_US.utf8"
     export LC_CTYPE="en_US.utf8"
+}
+
+start_lsass()
+{
+    sleep 1
+    echo -n " [starting lsass service] "
+    /usr/lib/vmware/likewise/bin/lwsm start lsass
+    sleep 1
+    /usr/lib/vmware/likewise/bin/lw-lsa get-status 2>&1 > /dev/null
+    if [ $? -ne 0 ]; then
+        failure=1
+        if [ `/usr/lib/vmware/likewise/bin/lwsm list | grep lsass | awk '{print $2}'` != "running" ]; then
+            echo -n " [retrying start of lsass service] "
+            /usr/lib/vmware/likewise/bin/lwsm start lsass
+        fi
+        i=1
+        while [ $failure -ne 0 -a $i -le 8 ]; do
+            sleep $i
+            i=$(($i*2))
+            /usr/lib/vmware/likewise/bin/lw-lsa get-status 2>&1 > /dev/null
+            failure=$?
+        done
+        if [ $failure -ne 0 ]; then
+            echo -n " [lsass service startup failure] "
+            return 1
+        fi
+    fi
 }
 
 . EXECDIR/init-base.sh
